version: '3'

services:
  fhir:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 3000
      MONGO_HOSTNAME: localhost
      MONGO_PORT: 27017
      RESOURCE_SERVER: http://localhost:3000/
      AUTH_SERVER_URI: http://myauthzserver.com
      CLIENT_ID: client
      CLIENT_SECRET: secret
      INTROSPECTION_URL: https://myauthzserver.com/introspect
    ports:
      - '3000:3000'
    volumes:
      - ./src:/srv/src/src
    command: yarn nodemon
