version: '3'

services:
  fhir:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 3001
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27018
      RESOURCE_SERVER: http://localhost:3000/
      AUTH_SERVER_URI: http://myauthzserver.com
      CLIENT_ID: client
      CLIENT_SECRET: secret
      INTROSPECTION_URL: https://myauthzserver.com/introspect
    ports:
      - '3001:3001'
    volumes:
      - ./src:/srv/src/src
    command: yarn nodemon

  mongo:
    image: mongo:3.6.1
    command: mongod --port 27018
    ports:
      - '27018:27018'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
