apiVersion: v1
kind: Service
metadata:
  name: fhirserverpublic
# namespace should match other services in this file  
  namespace: nodefhirservermongo 
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    io.kompose.service: fhir
